def build( bld ):
	bld.program(
		source = 'bgen_to_vcf.cpp',
		target = 'bgen_to_vcf',
		use = 'bgen zlib zstd',
		cxxflags = ['-std=c++11']
	)

	bld.program(
		source = 'count_alleles.cpp',
		target = 'count_alleles',
		use = 'bgen zlib zstd',
		cxxflags = ['-std=c++11']
	)
