# This is a sample build configuration for other languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        script:
          - apt-get install --assume-yes libbz2-1.0 libbz2-dev zlib1g-dev r-base
          - apt-get install --assume-yes python-pip
          - python -m pip install robotframework
          - ./waf-1.5.18 configure
          - ./waf-1.5.18
          - cd test/functional
          - mkdir -p test-reports
          - pybot -o NONE -l NONE -r NONE -d test-reports -x xunit.xml ./tests.txt

