image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        script:
          - apt-get install --assume-yes libbz2-1.0 libbz2-dev zlib1g-dev r-base
          - apt-get install --assume-yes python-pip
          - python -m pip install robotframework
          - ./waf-1.5.18 configure
          - ./waf-1.5.18
          - cd test/functional
          - mkdir -p test-reports
          - pybot -o NONE -l NONE -r NONE -d test-reports -x xunit.xml ./tests.txt

