# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bgen.load <- function(
	filename,
	ranges,
	max_entries_per_sample = 3,
	samples = NULL,
	index.filename = sprintf( "%s.bgi", filename )
) {
	if( !is.null( samples )) {
		.Call('rbgen_load_samples', PACKAGE = 'rbgen', filename, index.filename, ranges, max_entries_per_sample, samples)
	} else {
		.Call('rbgen_load', PACKAGE = 'rbgen', filename, index.filename, ranges, max_entries_per_sample)
	}
}

