# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

giveMeMyData <- function(filename, chromosome, start, end) {
    .Call('rbgen_giveMeMyData', PACKAGE = 'rbgen', filename, chromosome, start, end)
}

