# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bgen.load <- function(filename, ranges, max_entries_per_sample = 3 ) {
    .Call('rbgen_load', PACKAGE = 'rbgen', filename, ranges, max_entries_per_sample)
}

