def build( bld ):
	bld.stlib(
		target = 'db',
		source = bld.path.ant_glob( 'src/*.cpp' ),
		includes='./include',
		cxxflags = [ '-std=c++11' ],
		use = 'boost sqlite3',
		export_includes = './include'
	)
