import os.path

def build( bld ):
	sources = bld.path.ant_glob( 'src/*.cpp' )
	bld.stlib(
		target = 'db',
		source = sources,
		includes='./include',
		cxxflags = [],
		use = 'boost sqlite3',
		export_includes = './include'
	)
	# Copy files into rbgen package directory
	for source in sources:
		bld( rule = 'cp ${SRC} ${TGT}', source = source, target = '../R/rbgen/src/db/' + os.path.basename( source.abspath() ), always = True )
