def build( bld ):
	sources = [ 'NAMESPACE', 'DESCRIPTION', 'src/RcppExports.cpp', 'src/giveMeMyData.cpp', 'src/Makevars', 'R/RcppExports.R' ]
	for source in sources:
		bld( rule = 'cp ${SRC} ${TGT}', source = 'package/' + source, target = 'rbgen/' + source, always = True )
